name: ghpage
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -U pip
          pip install Sphinx sphinx-rtd-theme

      - name: build
        run: |
          . venv/bin/activate
          cd docs
          make clean
          make html

      - name: push
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "update doc"
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF}
            